name: Deploy Re4cto to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 23
      
    - name: Build app
      run: |
        npm install
        npm run build:gh
        
    - name: Create redirect script
      run: |
        cd dist
        cp index.html 404.html
        cat > redirect.js << 'EOL'
        (function() {
          var pathSegmentsToKeep = 1;
          var l = window.location;
          l.replace(
            l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
            l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
            l.pathname.split('/').slice(1 + pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
            (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
            l.hash
          );
         })();
         EOL
         sed -i '/<head>/a <script src="redirect.js"></script>' index.html
         cat > 404.html << 'EOL'
         <!DOCTYPE html>
         <html>
           <head>
             <meta charset="utf-8">
             <script>
               sessionStorage.redirect = location.href;
             </script>
             <meta http-equiv="refresh" content="0;URL='/'">
           </head>
           <body></body>
         </html>
         EOL
         sed -i '/<head>/a <script>if (sessionStorage.redirect) { window.history.replaceState(null, null, sessionStorage.redirect); delete sessionStorage.redirect; }</script>' index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
